version: "3.9"

services:
  fake-news-detector:
    build: .
    container_name: fake_news_detector
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=flask_api.py
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - ./app/database.json:/app/database.json
      - ./app/model.json:/app/model.json
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped
